# Based on https://github.com/psf/black/actions/runs/17913292/workflow

name: Black Style
on:
  push:
    paths: 
      - '**.py'
    branches:
      - develop
      - master
  pull_request:
    paths: 
      - '**.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
